# Generated by Django 4.2.5 on 2023-10-16 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('idAd', models.AutoField(primary_key=True, serialize=False)),
                ('nomAdm', models.CharField(max_length=20)),
                ('apeAdm', models.CharField(max_length=20)),
                ('correoAd', models.EmailField(max_length=254)),
                ('contraAd', models.CharField(max_length=128)),
                ('telAd', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('idConsulta', models.AutoField(primary_key=True, serialize=False)),
                ('diag', models.CharField(max_length=1028)),
            ],
        ),
        migrations.CreateModel(
            name='Estudios',
            fields=[
                ('idEst', models.AutoField(primary_key=True, serialize=False)),
                ('nomEst', models.CharField(max_length=15)),
                ('resu', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Expedientes',
            fields=[
                ('idEx', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('idMed', models.AutoField(primary_key=True, serialize=False)),
                ('nomMed', models.CharField(max_length=20)),
                ('apeMed', models.CharField(max_length=20)),
                ('especialidad', models.CharField(max_length=15)),
                ('cedula', models.IntegerField()),
                ('correoMed', models.EmailField(max_length=254)),
                ('contraMed', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('idPac', models.AutoField(primary_key=True, serialize=False)),
                ('nomPac', models.CharField(max_length=20)),
                ('apePac', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=30)),
                ('edad', models.PositiveSmallIntegerField()),
                ('correoPac', models.EmailField(max_length=254)),
                ('contraPac', models.CharField(max_length=128)),
                ('telPac', models.IntegerField()),
                ('sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino'), ('O', 'Otros')], max_length=1)),
                ('idMed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clinica.medico')),
            ],
        ),
    ]
