# Generated by Django 4.2.5 on 2023-10-16 19:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clinica', '0002_paciente_fecha_alter_medico_especialidad'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Estudios',
            new_name='Estudio',
        ),
        migrations.RenameModel(
            old_name='Expedientes',
            new_name='Expediente',
        ),
        migrations.AddField(
            model_name='consulta',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
