# Generated by Django 4.2.5 on 2023-10-16 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clinica', '0003_rename_estudios_estudio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='idMed',
        ),
        migrations.AddField(
            model_name='consulta',
            name='medico',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Clinica.medico'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='paciente',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Clinica.paciente'),
        ),
        migrations.AddField(
            model_name='estudio',
            name='paciente',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='Clinica.paciente'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='medico',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='Clinica.medico'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='paciente',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='Clinica.paciente'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='medico',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Clinica.medico'),
        ),
    ]
