# Generated by Django 4.2.5 on 2023-10-16 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clinica', '0004_remove_paciente_idmed_consulta_medico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='medico',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Clinica.medico'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='paciente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Clinica.paciente'),
        ),
        migrations.AlterField(
            model_name='estudio',
            name='paciente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Clinica.paciente'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='medico',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Clinica.medico'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='paciente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Clinica.paciente'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='medico',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Clinica.medico'),
        ),
    ]
