# Generated by Django 4.2.5 on 2023-10-18 02:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clinica', '0005_alter_consulta_medico_alter_consulta_paciente_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='fecha',
            new_name='fechanaci',
        ),
        migrations.AlterField(
            model_name='administrador',
            name='telAd',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe tener 10 dígitos.', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='medico',
            name='cedula',
            field=models.CharField(max_length=18),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='edad',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message='La edad debe ser mayor o igual a 1.'), django.core.validators.MaxValueValidator(120, message='La edad debe ser menor o igual a 120.')]),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telPac',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe tener 10 dígitos.', regex='^\\d{10}$')]),
        ),
    ]
