# Generated by Django 4.2.5 on 2023-10-18 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clinica', '0006_rename_fecha_paciente_fechanaci_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='medico',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Clinica.medico'),
        ),
    ]
