# Generated by Django 4.2.5 on 2023-10-23 14:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clinica', '0007_alter_paciente_medico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='edad',
            field=models.CharField(max_length=3, validators=[django.core.validators.MinValueValidator(1, message='La edad debe ser mayor o igual a 1.'), django.core.validators.MaxValueValidator(120, message='La edad debe ser menor o igual a 120.')]),
        ),
    ]
