# Generated by Django 4.2.5 on 2023-10-24 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clinica', '0008_alter_paciente_edad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='edad',
        ),
    ]
